/**
 * AI-powered commit message generation.
 *
 * Gathers changed files, diff stats, and compact diffs,
 * sends them to the configured AI provider, and returns a formatted message.
 */
import { exec } from 'node:child_process'
import { promisify } from 'node:util'
import { streamText } from 'ai'
import { DISABLED_REASONING_OPTIONS, getAIModel } from '../ai'
import { loadConfig } from '../config'

const execAsync = promisify(exec)
const COMPACT_DIFF_MAX = 2000

export async function generateCommitMessage(
  root: string,
): Promise<{ message?: string; modelName?: string; error?: string }> {
  try {
    const results = await Promise.allSettled([
      execAsync('git status --short', { cwd: root }),
      execAsync('git diff --stat', { cwd: root }),
      execAsync('git diff --cached --stat', { cwd: root }),
    ])

    const statusShort =
      results[0].status === 'fulfilled' ? results[0].value.stdout : ''
    const unstagedStat =
      results[1].status === 'fulfilled' ? results[1].value.stdout : ''
    const stagedStat =
      results[2].status === 'fulfilled' ? results[2].value.stdout : ''

    const changedFiles = statusShort
      .split('\n')
      .filter(Boolean)
      .map((line: string) => {
        const X = line[0]
        const Y = line[1]
        const file = line.slice(3).trim()
        const prefix = X !== ' ' && X !== '?' ? `[staged] ` : `[unstaged] `
        const typeMap: Record<string, string> = {
          M: 'modified',
          A: 'added',
          D: 'deleted',
          R: 'renamed',
          '?': 'untracked',
        }
        const statusType =
          X !== ' ' && X !== '?'
            ? typeMap[X] || 'changed'
            : typeMap[Y] || 'changed'
        return `${prefix}${statusType}: ${file}`
      })
      .join('\n')

    if (!changedFiles) {
      console.warn(
        '[CommitGen] No changed files found. statusShort:',
        JSON.stringify(statusShort),
      )
      return { error: 'No changes to commit' }
    }

    let detailContext = ''
    for (const flag of ['--cached', '']) {
      try {
        const { stdout: diff } = await execAsync(
          `git diff ${flag} --unified=2`,
          { cwd: root, maxBuffer: 1024 * 10 },
        )
        if (diff.length > 0 && diff.length < COMPACT_DIFF_MAX) {
          detailContext += `\n${flag ? 'Staged' : 'Unstaged'} diff:\n${diff.slice(0, COMPACT_DIFF_MAX)}`
        }
      } catch {
        // skip if too large
      }
    }

    const statBlock = [stagedStat?.trim(), unstagedStat?.trim()]
      .filter(Boolean)
      .join('\n')
    const diffContent = `Files changed:\n${changedFiles}\n\nStats:\n${statBlock}${detailContext}`

    const mainConfig = await loadConfig()
    const aiConfig = mainConfig?.ai
    if (!aiConfig?.providers || aiConfig.providers.length === 0) {
      return { error: 'No AI provider configured' }
    }

    const activeId = aiConfig.activeId
    const activeProvider: any =
      aiConfig.providers.find((p: any) => p.id === activeId) ||
      aiConfig.providers[0]

    const modelName = activeProvider.model || activeProvider.name || 'AI'

    let model
    try {
      model = await getAIModel(activeProvider)
    } catch (modelErr: unknown) {
      const msg =
        modelErr instanceof Error ? modelErr.message : String(modelErr)
      console.error('[CommitGen] Failed to create AI model:', msg)
      return { error: `AI model error: ${msg}` }
    }

    const systemPrompt = `You generate short commit messages only. Never reason or think aloud — output just the commit message.

Format:
{type}: {short summary}

- {specific change}
- {specific change}

Type: feat, fix, chore, refactor, docs, test, style.
Last line: Generated by Aynite (${modelName})

Example:
feat: add user authentication

- Implement login form with validation
- Add JWT token generation
- Store session data

Generated by Aynite (${modelName})`

    const userMessage = `Write a commit message for:

${diffContent.slice(0, 1200)}`

    let text: string
    try {
      const controller = new AbortController()
      const timeout = setTimeout(() => controller.abort(), 30000)
      const result = streamText({
        model,
        system: systemPrompt,
        messages: [{ role: 'user', content: userMessage }],
        maxOutputTokens: 300,
        temperature: 0.6,
        abortSignal: controller.signal,
        providerOptions: DISABLED_REASONING_OPTIONS,
      })

      let fullText = ''
      for await (const part of result.fullStream) {
        if (part.type === 'text-delta') {
          fullText += part.text
        }
      }
      clearTimeout(timeout)
      text = fullText
    } catch (genErr: unknown) {
      const genMsg = genErr instanceof Error ? genErr.message : String(genErr)
      console.error('[CommitGen] streamText threw:', genMsg)
      return { error: `AI generation failed: ${genMsg}` }
    }

    if (!text?.trim()) {
      console.error('[CommitGen] streamText returned empty text')
      return { error: 'AI returned empty response' }
    }

    const body = text
      .replace(/^```(?:text)?\n?/, '')
      .replace(/\n?```$/, '')
      .trim()

    if (!body) {
      console.error(
        '[CommitGen] Cleaned message is empty. Raw text:',
        JSON.stringify(text),
      )
      return { error: 'Failed to generate a commit message' }
    }

    const message = body.includes('Generated by Aynite')
      ? body
      : `${body}\n\nGenerated by Aynite (${modelName})`

    return { message, modelName }
  } catch (e: unknown) {
    const errorMsg = e instanceof Error ? e.message : String(e)
    console.error(
      '[CommitGen] Generate failed:',
      errorMsg,
      e instanceof Error ? e.stack : '',
    )
    return { error: errorMsg }
  }
}
