version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: "increase"
    groups:
      production-deps:
        dependency-type: "production"
        update-types: ["patch", "minor"]
      dev-deps:
        dependency-type: "development"
        update-types: ["patch", "minor"]
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    labels:
      - "dependencies"
