export const DEFAULT_THEMES: Record<string, any> = {
  light: {
    name: 'Light',
    type: 'light',
    isSystem: true,
    colors: {
      background: '#ffffff',
      foreground: '#09090b',
      sidebar: '#f4f4f5',
      card: '#ffffff',
      cardForeground: '#09090b',
      popover: '#ffffff',
      popoverForeground: '#09090b',
      primary: '#18181b',
      primaryForeground: '#fafafa',
      secondary: '#f4f4f5',
      secondaryForeground: '#18181b',
      muted: '#f4f4f5',
      mutedForeground: '#71717a',
      accent: '#f4f4f5',
      accentForeground: '#18181b',
      destructive: '#ef4444',
      destructiveForeground: '#fafafa',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#18181b',
      selection: '#bfdbfe',
      selectionForeground: '#1e3a5f',
      link: '#2563eb',
      success: '#16a34a',
      successForeground: '#f0fdf4',
      warning: '#ca8a04',
      warningForeground: '#fefce8',
      info: '#2563eb',
      infoForeground: '#eff6ff',
      tabActive: '#ffffff',
      tabActiveBorder: '#3b82f6',
      scrollbarThumb: '#d4d4d8',
      scrollbarTrack: 'transparent',
    },
    fonts: {
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      fontMono: 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace',
      fontSize: '14px',
    },
  },
  dark: {
    name: 'Dark',
    type: 'dark',
    isSystem: true,
    colors: {
      background: '#09090b',
      foreground: '#fafafa',
      sidebar: '#121214',
      card: '#09090b',
      cardForeground: '#fafafa',
      popover: '#09090b',
      popoverForeground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#18181b',
      secondary: '#27272a',
      secondaryForeground: '#fafafa',
      muted: '#27272a',
      mutedForeground: '#a1a1aa',
      accent: '#27272a',
      accentForeground: '#fafafa',
      destructive: '#7f1d1d',
      destructiveForeground: '#fafafa',
      border: '#27272a',
      input: '#27272a',
      ring: '#d4d4d8',
      selection: '#264f78',
      selectionForeground: '#ffffff',
      link: '#60a5fa',
      success: '#22c55e',
      successForeground: '#052e16',
      warning: '#eab308',
      warningForeground: '#422006',
      info: '#3b82f6',
      infoForeground: '#eff6ff',
      tabActive: '#09090b',
      tabActiveBorder: '#3b82f6',
      scrollbarThumb: '#27272a',
      scrollbarTrack: 'transparent',
    },
    fonts: {
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      fontMono: 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace',
      fontSize: '14px',
    },
  },
  aurora: {
    name: 'Aurora',
    type: 'dark',
    isSystem: true,
    colors: {
      background: '#0f0e17',
      foreground: '#e0def4',
      sidebar: '#141220',
      card: '#1a1826',
      cardForeground: '#e0def4',
      popover: '#1a1826',
      popoverForeground: '#e0def4',
      primary: '#a78bfa',
      primaryForeground: '#0f0e17',
      secondary: '#2a2540',
      secondaryForeground: '#e0def4',
      muted: '#221f35',
      mutedForeground: '#908caa',
      accent: '#2a2540',
      accentForeground: '#e0def4',
      destructive: '#eb6f92',
      destructiveForeground: '#0f0e17',
      border: '#393552',
      input: '#2a2540',
      ring: '#a78bfa',
      selection: '#3e1f79',
      selectionForeground: '#e0def4',
      link: '#7dd3fc',
      success: '#4ade80',
      successForeground: '#052e16',
      warning: '#fbbf24',
      warningForeground: '#422006',
      info: '#818cf8',
      infoForeground: '#eef2ff',
      tabActive: '#0f0e17',
      tabActiveBorder: '#a78bfa',
      scrollbarThumb: '#393552',
      scrollbarTrack: 'transparent',
    },
    fonts: {
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      fontMono: 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace',
      fontSize: '14px',
    },
  },
  ember: {
    name: 'Ember',
    type: 'dark',
    isSystem: true,
    colors: {
      background: '#1a1210',
      foreground: '#f5e6d3',
      sidebar: '#151010',
      card: '#231c18',
      cardForeground: '#f5e6d3',
      popover: '#231c18',
      popoverForeground: '#f5e6d3',
      primary: '#f59e0b',
      primaryForeground: '#1a1210',
      secondary: '#2d2420',
      secondaryForeground: '#f5e6d3',
      muted: '#2d2420',
      mutedForeground: '#a89585',
      accent: '#2d2420',
      accentForeground: '#f5e6d3',
      destructive: '#dc2626',
      destructiveForeground: '#fef2f2',
      border: '#3d322c',
      input: '#2d2420',
      ring: '#f59e0b',
      selection: '#78350f',
      selectionForeground: '#fef3c7',
      link: '#fbbf24',
      success: '#84cc16',
      successForeground: '#1a2e05',
      warning: '#f59e0b',
      warningForeground: '#451a03',
      info: '#fb923c',
      infoForeground: '#fff7ed',
      tabActive: '#1a1210',
      tabActiveBorder: '#f59e0b',
      scrollbarThumb: '#3d322c',
      scrollbarTrack: 'transparent',
    },
    fonts: {
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      fontMono: 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace',
      fontSize: '14px',
    },
  },
  nord: {
    name: 'Nord',
    type: 'dark',
    isSystem: true,
    colors: {
      background: '#2e3440',
      foreground: '#d8dee9',
      sidebar: '#242831',
      card: '#3b4252',
      cardForeground: '#e5e9f0',
      popover: '#3b4252',
      popoverForeground: '#e5e9f0',
      primary: '#88c0d0',
      primaryForeground: '#2e3440',
      secondary: '#434c5e',
      secondaryForeground: '#eceff4',
      muted: '#3b4252',
      mutedForeground: '#a1a1aa',
      accent: '#434c5e',
      accentForeground: '#eceff4',
      destructive: '#bf616a',
      destructiveForeground: '#eceff4',
      border: '#4c566a',
      input: '#434c5e',
      ring: '#88c0d0',
      selection: '#434c5e',
      selectionForeground: '#eceff4',
      link: '#88c0d0',
      success: '#a3be8c',
      successForeground: '#2e3440',
      warning: '#ebcb8b',
      warningForeground: '#2e3440',
      info: '#81a1c1',
      infoForeground: '#eceff4',
      tabActive: '#2e3440',
      tabActiveBorder: '#88c0d0',
      scrollbarThumb: '#4c566a',
      scrollbarTrack: 'transparent',
    },
    fonts: {
      fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
      fontMono: 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace',
      fontSize: '14px',
    },
  },
}
